---
- name: Establishes a single-node Aurora cluster
  hosts: aurora
  sudo: true

  roles:
    - role: docker
      docker_roles:
        - docker
        - registry

    - role: zookeeper
      zookeeper_hosts: "{{ groups['aurora']|join(',') }}"

    - role: mesos
      mesos_zookeeper_quorum: "{{ groups['aurora']|join(',') }}"
      mesos_containerizers:
        - docker
        - mesos
      mesos_roles:
        - master
        - slave

    - role: thermos

    - role: aurora
      aurora_schedulers: "{{ groups['aurora']|join(',') }}"
      aurora_zookeeper_quorum: "{{ groups['aurora']|join(',') }}"
