---
- name: Establishes a single-node Aurora cluster
  hosts: aurora
  sudo: true

  roles:
    - role: docker
    - role: zookeeper
      zookeeper_hosts: "{{ groups['aurora'] }}"
    - role: mesos
      mesos_zookeeper_quorum: "{{ groups['aurora'] }}"
      mesos_roles:
        - master
        - slave
    - thermos
