---
- name: Establishes a single-node Aurora cluster
  hosts: tag_ansible_group_aurora
  sudo: true

  vars:
    aurora_roles:
      - client
      - scheduler
    aurora_schedulers: 127.0.0.1
    aurora_zookeeper_quorum: 127.0.0.1
    docker_roles:
      - docker
      - registry
    mesos_zookeeper_quorum: 127.0.0.1
    mesos_containerizers:
      - docker
      - mesos
    mesos_roles:
      - master
      - slave
    zookeeper_hosts: 127.0.0.1

  roles:
    - docker
    - zookeeper
    - mesos
    - thermos
    - aurora
