---
- name: Install necessary packages for Ansible apt integreation
  apt: name="{{ item }}"
       state=present
       force=yes
  with_items:
    - apt-transport-https
    - python-apt

- name: Ensure that apt cache is up-to-date
  apt:
    update_cache: yes
    cache_valid_time: 3600
