---
- include: Debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - thrift

- include: RedHat.yml
  when: ansible_os_family == "RedHat"
  tags:
    - thrift

- name: Download Thrift release tarball
  get_url:
    url: "{{ apache_mirror_base }}/thrift/{{ thrift_version }}/thrift-{{ thrift_version }}.tar.gz"
    dest: "{{ source_dir }}/thrift-{{ thrift_version }}.tar.gz"
  register: thrift_download
  tags:
    - thrift

- name: Untar Thrift release tarball
  command: "tar xzf {{ source_dir }}/thrift-{{ thrift_version }}.tar.gz"
  args:
    chdir: "{{ source_dir }}"
  when: thrift_download.changed
  tags:
    - thrift

- name: Configure Thrift build
  command: "./configure --prefix='{{ install_dir }}' --with-lua=no"
  args:
    chdir: "{{ source_dir }}/thrift-{{ thrift_version }}"
  when: thrift_download.changed
  tags:
    - thrift

- name: Build Thrift
  command: make
  args:
    chdir: "{{ source_dir }}/thrift-{{ thrift_version }}"
  when: thrift_download.changed
  tags:
    - thrift

- name: Install Thrift
  command: make install
  args:
    chdir: "{{ source_dir }}/thrift-{{ thrift_version }}"
  when: thrift_download.changed
  tags:
   - thrift
