---
- name: Ensure that Thrift build dependencies are satisfied
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - ant
    - automake
    - bison
    - boost-devel
    - flex
    - gcc-c++
    - libevent-devel
    - libtool
    - make
    - openssl-devel
    - pkgconfig
    - zlib-devel
