---
- name: Install necessary packages for building Python
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - bzip2-devel
    - gcc
    - gcc-c++
    - make
    - openssl-devel
    - ncurses-devel
    - paco
    - sqlite-devel
    - zlib-devel
