---
- include: Debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - daemonize

- include: RedHat.yml
  when: ansible_os_family == "RedHat"
  tags:
    - daemonize

- include: build.yml
  tags:
    - daemonize
