---
- include: Debian.yml
  when: ansible_os_family == "Debian"

- include: RedHat.yml
  when: ansible_os_family == "RedHat" and not build_from_source

- include: build.yml
  when: ansible_os_family == "Debian" or build_from_source
