---
- name: Ensure that cluster name is an a templatable state
  set_fact:
    safe_mesos_cluster_name: "{{ mesos_cluster_name | regex_replace(' ', '_') }}"
  tags:
    - mesos

- name: Ensure that the appropriate Mesos package name is selected
  set_fact:
    mesos_pkgname: "mesos-{{ mesos_version }}"
  when: mesos_version != "latest"
  tags:
    - mesos

- name: Ensure that Mesos-specific facts are set
  set_fact:
    mesos_pkgname: mesos
  when: mesos_version == "latest"
  tags:
    - mesos

- include: Debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - mesos

- include: RedHat.yml
  when: ansible_os_family == "RedHat"
  tags:
    - mesos

- name: Ensure that Mesos master work directory exists
  file:
    path: "{{ mesos_work_dir }}/{{ safe_mesos_cluster_name }}/master"
    state: directory
    recurse: yes
  when: '"master" in mesos_roles'
  tags:
    - mesos
    - mesos_master

- name: Ensure that Mesos slave work directory exists
  file:
    path: "{{ mesos_work_dir }}/{{ safe_mesos_cluster_name }}/slave"
    state: directory
    recurse: yes
  when: '"slave" in mesos_roles'
  tags:
    - mesos
    - mesos_slave

- name: Ensure that Mesos master log directory exists
  file:
    path: "{{ mesos_log_dir }}/{{ safe_mesos_cluster_name }}/master"
    state: directory
    recurse: yes
  when: '"master" in mesos_roles'
  tags:
    - mesos
    - mesos_master

- name: Ensure that Mesos slave log directory exists
  file:
    path: "{{ mesos_log_dir }}/{{ safe_mesos_cluster_name }}/slave"
    state: directory
    recurse: yes
  when: '"slave" in mesos_roles'
  tags:
    - mesos
    - mesos_slave

- name: Ensure that Mesos master state directory exists
  file:
    path: "{{ mesos_state_dir }}/{{ safe_mesos_cluster_name }}/master"
    state: directory
    recurse: yes
  when: '"master" in mesos_roles'
  tags:
    - mesos
    - mesos_master

- name: Ensure that Mesos slave state directory exists
  file:
    path: "{{ mesos_state_dir }}/{{ safe_mesos_cluster_name }}/slave"
    state: directory
    recurse: yes
  when: '"slave" in mesos_roles'
  tags:
    - mesos
    - mesos_slave

- name: Ensure that prepackaged Mesos state files are removed
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/mesos-master/quorum
    - /etc/mesos-master/work_dir
  tags:
    - mesos

- name: Template Mesos ZooKeeper quorum file
  template:
    src: zk.j2
    dest: "{{ mesos_conf_dir }}/zk"
  tags:
    - mesos
    - mesos_config

- name: Template Mesos base /etc/default file
  template:
    src: base-defaults.j2
    dest: /etc/default/mesos
  tags:
    - mesos
    - mesos_config

- name: Template Mesos master /etc/default file
  template:
    src: master-defaults.j2
    dest: /etc/default/mesos-master
  when: '"master" in mesos_roles'
  tags:
    - mesos
    - mesos_config
    - mesos_master

- name: Template Mesos slave /etc/default file
  template:
    src: slave-defaults.j2
    dest: /etc/default/mesos-slave
  when: '"slave" in mesos_roles'
  tags:
    - mesos
    - mesos_config
    - mesos_slave

- name: Template Mesos cluster daemon control script
  template:
    src: mesos-control.sh.j2
    dest: "/usr/bin/mesos-{{ safe_mesos_cluster_name }}"
    mode: 0755
  tags:
    - mesos

- name: Ensure that Mesos master process is running
  command: "/usr/bin/mesos-{{ safe_mesos_cluster_name }} master start"
  args:
    creates: "{{ mesos_state_dir }}/{{ safe_mesos_cluster_name }}/master.pid"
  when: '"master" in mesos_roles'
  tags:
    - mesos
    - mesos_master

- name: Ensure that Mesos slave process is running
  command: "/usr/bin/mesos-{{ safe_mesos_cluster_name }} slave start"
  args:
    creates: "{{ mesos_state_dir }}/{{ safe_mesos_cluster_name }}/slave.pid"
  when: '"slave" in mesos_roles'
  tags:
    - mesos
    - mesos_slave

- name: Setup a Monit configuration for the Mesos master
  template:
    src: mesos-master.monit.j2
    dest: "/etc/monit.d/mesos-{{ safe_mesos_cluster_name }}-master"
  notify:
    - Reload Monit
  when: '"master" in mesos_roles'
  register: mesos_master_monit
  tags:
    - mesos
    - mesos_config
    - mesos_master

- name: Setup a Monit configuration for the Mesos slave
  template:
    src: mesos-slave.monit.j2
    dest: "/etc/monit.d/mesos-{{ safe_mesos_cluster_name }}-slave"
  notify:
    - Reload Monit
  when: '"slave" in mesos_roles'
  register: mesos_slave_monit
  tags:
    - mesos
    - mesos_config
    - mesos_slave

- name: Ensure that Monit is loaded with latest configuration
  service:
    name: monit
    state: reloaded
  when: mesos_master_monit.changed or mesos_slave_monit.changed
  tags:
    - mesos
    - mesos_config

- name: Wait for Monit to get its act together
  pause:
    seconds: 5
  when: mesos_master_monit.changed or mesos_slave_monit.changed
  tags:
    - mesos
    - mesos_config

- name: Ensure that the Mesos master is monitored by Monit
  monit:
    name: "mesos-master-{{ safe_mesos_cluster_name }}"
    state: monitored
  when: '"master" in mesos_roles'
  tags:
    - mesos
    - mesos_master

- name: Ensure that the Mesos slave is monitored by Monit
  monit:
    name: "mesos-slave-{{ safe_mesos_cluster_name }}"
    state: monitored
  when: '"slave" in mesos_roles'
  tags:
    - mesos
    - mesos_slave

- name: Write a Mesos logrotate
  template:
    src: mesos.logrotate.j2
    dest: "/etc/logrotate.d/mesos-{{ safe_mesos_cluster_name }}"
    mode: 0644
  tags:
    - mesos
