---
- name: Ensure that Mesosphere repository is present
  yum:
    name: "{{ mesos_repo_rpm }}"
    state: present

- name: Ensure that Mesos and its dependencies are present
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ mesos_pkgname }}"
