---
aurora_version: 0.9.0

aurora_schedulers: []

aurora_roles:
  - client
  - scheduler

aurora_cluster_name: main

aurora_serverset_zk_path: /aurora/scheduler
aurora_native_log_zk_path: /aurora/replicated-log

aurora_state_dir: /var/run/aurora
aurora_native_log_path: db
aurora_backup_path: backups

aurora_native_log_quorum_size: 1

aurora_jvm_flags: []
aurora_extra_flags: []

aurora_enable_beta_updater: true

aurora_http_port: 8081
aurora_libprocess_port: 8083

aurora_http_timeout_secs: 2
aurora_restart_cycles: 10

aurora_zookeeper_quorum: []
aurora_zookeeper_port: 2181

aurora_zookeeper_username: ""
aurora_zookeeper_password: ""

aurora_log_level: INFO

aurora_bin_dir: /usr/bin/aurora
aurora_conf_dir: /etc/aurora
aurora_lib_dir: /usr/lib/aurora
aurora_log_dir: /var/log/aurora

aurora_jvm_home: /usr/lib/jvm/jre
