---
- name: Workaround ansible_lsb bug by re-running setup module
  setup:
  tags:
    - thermos

- name: Ensure that Thermos directories exist
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ thermos_bin_dir }}/{{ thermos_version }}"
    - "{{ thermos_log_dir }}"
    - "{{ thermos_state_dir }}"
  tags:
    - thermos

- name: Download Thermos binaries
  get_url:
    url: "{{ thermos_mirror_base }}/{{ thermos_version }}/thermos/mesos-{{ mesos_version }}/{{ ansible_os_family }}/{{ ansible_lsb.major_release }}/{{ item }}.pex"
    dest: "{{ thermos_bin_dir }}/{{ thermos_version }}/{{ item }}"
  with_items: thermos_binaries
  tags:
    - thermos

- name: Ensure that Thermos binaries are executable
  file:
    path: "{{ thermos_bin_dir }}/{{ thermos_version }}/{{ item }}"
    mode: 0755
  with_items: thermos_binaries
  tags:
    - thermos

- include: observer.yml
  when: "'observer' in thermos_roles"
