---
- name: Workaround ansible_lsb bug by re-running setup module
  setup:
  tags:
    - thermos

- name: Ensure that the Aurora Yum repository is present
  template:
    src: ssalevan_aurora.repo.j2
    dest: /etc/yum.repos.d/ssalevan_aurora.repo
    mode: 0644
  tags:
    - thermos

- name: Install the Aurora RPM
  yum:
    name: aurora-thermos
    state: present
    enablerepo: ssalevan_aurora
  tags:
    - thermos

- include: observer.yml
  when: "'observer' in thermos_roles"
  tags:
    - thermos