---
- name: Workaround ansible_lsb bug by re-running setup module
  setup:
  tags:
    - thermos

- name: Ensure that Thermos binary directory exists
  file:
    path: "{{ thermos_bin_path }}/{{ thermos_version }}"
    state: directory
    recurse: yes
  tags:
    - thermos

- name: Download Thermos binaries
  get_url:
    url: "{{ thermos_mirror_base }}/{{ thermos_version }}/thermos/mesos-{{ mesos_version }}/{{ ansible_os_family }}/{{ ansible_lsb.major_release }}/{{ item }}.pex"
    dest: "{{ thermos_bin_path }}/{{ thermos_version }}/{{ item }}"
  with_items:
    - gc_executor
    - thermos_executor
    - thermos_observer
    - thermos_runner
  tags:
    - thermos

- name: Ensure that Thermos binaries are executable
  file:
    path: "{{ thermos_bin_path }}/{{ thermos_version }}/{{ item }}"
    mode: 0755
  with_items:
    - gc_executor
    - thermos_executor
    - thermos_observer
    - thermos_runner
  tags:
    - thermos
