---
- name: Template the Thermos observer startup script
  template:
    src: observer-startup.sh.j2
    dest: "{{ thermos_bin_dir }}/{{ thermos_version }}/observer_startup"
    mode: 0755
  tags:
    - thermos
    - thermos_observer

- name: Template the Thermos observer control script
  template:
    src: observer-control.sh.j2
    dest: "{{ thermos_bin_dir }}/{{ thermos_version }}/observer_control"
    mode: 0755
  tags:
    - thermos
    - thermos_observer

- name: Ensure that the Thermos observer daemon is running
  shell: "{{ thermos_bin_dir }}/{{ thermos_version }}/observer_control start"
  args:
    creates: "{{ thermos_state_dir }}/observer.pid"
  tags:
    - thermos
    - thermos_observer

- name: Setup a Monit configuration for the Thermos observer
  template:
    src: thermos-observer.monit.j2
    dest: /etc/monit.d/thermos-observer
  register: thermos_observer_monit
  tags:
    - thermos
    - thermos_observer

- name: Ensure that Monit is loaded with latest configuration
  service:
    name: monit
    state: reloaded
  when: thermos_observer_monit.changed
  tags:
    - thermos
    - thermos_observer

- name: Wait for Monit to get its act together
  pause:
    seconds: 10
  when: thermos_observer_monit.changed
  tags:
    - thermos
    - thermos_observer

- name: Ensure that the Thermos observer daemon is monitored by Monit
  monit:
    name: thermos-observer
    state: monitored
  tags:
    - thermos
    - thermos_observer
