---
- name: Ensure that the Thermos observer daemon is running
  service:
    name: thermos
    state: started
  tags:
    - thermos
    - thermos_observer

- name: Setup a Monit configuration for the Thermos observer
  template:
    src: thermos-observer.monit.j2
    dest: /etc/monit.d/thermos-observer
  register: thermos_observer_monit
  tags:
    - thermos
    - thermos_observer

- name: Ensure that Monit is loaded with latest configuration
  service:
    name: monit
    state: reloaded
  when: thermos_observer_monit.changed
  tags:
    - thermos
    - thermos_observer

- name: Wait for Monit to get its act together
  pause:
    seconds: 10
  when: thermos_observer_monit.changed
  tags:
    - thermos
    - thermos_observer

- name: Ensure that the Thermos observer daemon is monitored by Monit
  monit:
    name: thermos-observer
    state: monitored
  tags:
    - thermos
    - thermos_observer
