---
ruby_version: "2.0.0-p353"

ruby_archive: ftp://ftp.ruby-lang.org/pub/ruby/2.0/ruby-{{ ruby_version }}.tar.gz

ruby_source_dir: /usr/src
ruby_install_dir: /usr

ruby_configure_options: --enable-shared
