---
- include: Debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - stunnel

- include: RedHat.yml
  when: ansible_os_family == "RedHat"
  tags:
    - stunnel

- name: Ensure that the stunnel group is created
  group:
    name: "{{ stunnel_group }}"
  tags:
    - stunnel

- name: Ensure that the stunnel user is created
  user:
    name: "{{ stunnel_user }}"
    group: "{{ stunnel_group }}"
  tags:
    - stunnel

- name: Ensure that stunnel directories are created and properly owned
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ stunnel_user }}"
    group: "{{ stunnel_group }}"
    recurse: yes
  with_items:
    - /var/run/stunnel4
  tags:
    - stunnel

- include: ssl.yml
  tags:
    - stunnel

- name: Template the stunnel configuration
  template:
    src: stunnel.conf.j2
    dest: /etc/stunnel/stunnel.conf
    owner: "{{ stunnel_user }}"
    group: "{{ stunnel_group }}"
    mode: 0644
  notify:
    - Restart stunnel via Monit
  tags:
    - stunnel

- name: Template the stunnel monit configuration
  template:
    src: stunnel.monit.j2
    dest: /etc/monit.d/stunnel.conf
    owner: root
    group: root
    mode: 0644
  register: stunnel_monit
  notify:
    - Reload Monit
  tags:
    - stunnel

- name: Ensure that the stunnel service is running
  service:
    name: stunnel
    state: started
    enabled: yes
  tags:
    - stunnel

- name: Ensure that Monit is loaded with latest configuration
  service:
    name: monit
    state: reloaded
  when: stunnel_monit.changed
  tags:
    - stunnel

- name: Wait for Monit to get its act together
  pause:
    seconds: 10
  when: stunnel_monit.changed
  tags:
    - stunnel

- name: Ensure that stunnel is monitored by Monit
  monit:
    name: stunnel
    state: monitored
  tags:
    - stunnel
