---
- name: Check if ElasticHQ monitoring plugin has been installed
  stat:
    path: "{{ elasticsearch_plugin_dir }}/HQ"
  register: elastichq_plugin_dir

- name: Install ElasticHQ monitoring plugin
  shell: bin/plugin -i royrusso/elasticsearch-HQ
  args:
    chdir: "{{ elasticsearch_home_dir }}"
  when: not elastichq_plugin_dir.stat.exists

- name: Ensure that all plugin contents are properly owned
  file:
    path: "{{ elasticsearch_plugin_dir }}"
    state: directory
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    recurse: yes
