---
- include: Debian.yml
  when: ansible_os_family == "Debian"

- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Add Docker monit configuration
  template:
    src: docker.monit.j2
    dest: /etc/monit.d/docker.conf
  notify:
    - Reload Monit

- name: Install Docker Python libraries to enable Ansible integration
  pip:
    name: docker-py
    state: present

- name: Ensure that the Docker service is running
  service:
    name: docker
    state: running
    enabled: yes
  tags: redock

- name: Complete the docking procedure by logging into the Docker Hub
  shell: docker login --email="{{ docker_email }}" --username="{{ docker_username }}" --password="{{ docker_password }}"
  tags: redock
