---
galaxy_info:
  author: Steve Salevan <steve.salevan@gmail.com>
  description: Installs and configures Apache Thrift
  license: Apache 2
  min_ansible_version: 1.2

dependencies:
  - role: apt
  - role: autoconf
  - role: automake
  - role: bison
  - role: epel
