---
openldap_roles:
  - client
  - server

openldap_schemas:
  - base
  - users_and_groups
  - dev_user

openldap_user: ldap
openldap_group: ldap

openldap_master_host: localhost

openldap_failure_cycles_before_restart: 2
openldap_restart_cycles_before_timeout: 5

# The auth domain to configure OpenLDAP servers and clients with
openldap_domain_name: example.com
openldap_dc: "dc={{ openldap_domain_name.split('.')[0] }},dc={{ openldap_domain_name.split('.')[1] }}"

openldap_database_type: mdb
openldap_database_maxsize_mb: 16834

openldap_root_user: Manager
openldap_root_password: changeme

# Configuration and initial LDIF schema
openldap_conf_dir: /etc/openldap
openldap_certs_path: certs
openldap_ldif_path: ldif

openldap_state_dir: /var/lib/slapd

openldap_enable_ssl: true
openldap_country: US
openldap_state: North Carolina
openldap_location: Raleigh
openldap_organization: Phil Collins Incorporated
openldap_organization_description: A Phil Collins Company
