---
- name: Remove installed Ruby RPMs
  yum:
    name: "{{ item }}"
    state: removed
  with_items:
    - ruby
    - ruby-libs

- name: Install necessary packages for building Ruby
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - gcc
    - gcc-c++
    - make
    - zlib-devel
    - openssl-devel
    - readline-devel
    - ncurses-devel
    - gdbm-devel
    - db4-devel
    - libffi-devel
    - tk-devel
    - libyaml
    - libyaml-devel
    - paco

- name: Download the Ruby archive requested via ruby_ver
  get_url:
    url: "{{ ruby_archive }}"
    dest: "{{ download_path }}/ruby-{{ ruby_ver }}.tar.gz"

- name: Extract the Ruby archive
  command: "tar xzf ruby-{{ ruby_ver }}.tar.gz"
  args:
    chdir: "{{ download_path }}"
    creates: "{{ download_path }}/ruby-{{ ruby_ver }}"

- name: Configure the Ruby build environment
  command: "./configure --prefix={{ install_prefix }} {{ configure_options }}"
  args:
    chdir: "{{ download_path }}/ruby-{{ ruby_ver }}"
    creates: "{{ install_prefix }}/bin/ruby"

- name: Build all Ruby binaries
  command: make
  args:
    chdir: "{{ download_path }}/ruby-{{ ruby_ver }}"
    creates: "{{ install_prefix }}/bin/ruby"

- name: Install Ruby via paco for ease of upgrading
  command: paco -D make install
  args:
    chdir: "{{ download_path }}/ruby-{{ ruby_ver }}"
    creates: "{{ install_prefix }}/bin/ruby"

- name: Install Bundler gem
  gem:
    name: bundler
    state: present
